In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


# Load CIFAR-10 dataset using TensorFlow
(train_images, train_labels), _ = tf.keras.datasets.cifar10.load_data()


# Flatten images based on RGB channels
num_samples = train_images.shape[0]  # Number of samples (images)
num_pixels = train_images.shape[1] * train_images.shape[2] * train_images.shape[3]  # Number of pixels per image

# Reshape the images to 1D arrays
flattened_images = train_images.reshape(num_samples, num_pixels)

# Print the shape of the flattened images
print("Shape of flattened images array:", flattened_images.shape)

# Flatten images based on RGB channels
num_samples = train_images.shape[0]  # Number of samples (images)
num_pixels = train_images.shape[1] * train_images.shape[2] * train_images.shape[3]  # Number of pixels per image

# Reshape the images to 1D arrays
flattened_images = train_images.reshape(num_samples, num_pixels)

# Create a DataFrame with pixel values and labels
df_images = pd.DataFrame(flattened_images)

# Add the label column to the DataFrame
df_images['Label'] = train_labels.flatten()

# Display the DataFrame
df_images

Shape of flattened images array: (50000, 3072)


0    1    2    3    4    5    6    7    8    9  ...  3063  3064  \
0       59   62   63   43   46   45   50   48   43   68  ...   216   184   
1      154  177  187  126  137  136  105  104   95  102  ...   143   133   
2      255  255  255  253  253  253  253  253  253  253  ...    78    85   
3       28   25   10   37   34   19   38   35   20   42  ...    54    47   
4      170  180  198  168  178  196  177  185  203  183  ...    75    79   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
49995  145  161  194  151  166  199  156  171  205  155  ...    39    41   
49996  255  245  132  254  247  134  255  249  137  254  ...   249   174   
49997   35  178  235   40  176  239   42  176  241   39  ...    27    52   
49998  189  211  240  186  208  236  185  207  235  184  ...   195   184   
49999  229  229  239  236  237  247  234  236  247  231  ...   179   177   

       3065  3066  3067  3068  3069  3070  3071  Label  
0       140   151   118    84   123    92    72      6  
1       139   143   134   142   143   133   144      9  
2        83    79    85    83    80    86    84      9  
3        28    63    56    37    72    65    46      4  
4        82    71    75    78    73    77    80      1  
...     ...   ...   ...   ...   ...   ...   ...    ...  
49995    56    36    38    53    37    39    54      2  
49996    79   252   181    81   253   181    76      6  
49997    77    21    43    66    12    31    50      9  
49998   169   196   189   171   195   190   171      1  
49999   173   164   164   162   163   163   161      1  

[50000 rows x 3073 columns]

In [2]:

# Create a StandardScaler object
scaler = StandardScaler()

# Fit the scaler to the features (excluding the 'Label' column)
scaler.fit(df_images.drop('Label', axis=1))

# Transform the features
scaled_features = scaler.transform(df_images.drop('Label', axis=1))

# Create a new DataFrame with the scaled features
df_images_scaled = pd.DataFrame(scaled_features, columns=df_images.columns[:-1])

# Add the 'Label' column to the scaled DataFrame
df_images_scaled['Label'] = df_images['Label']

# Display the DataFrame
df_images=df_images_scaled

df_images

0         1         2         3         4         5         6  \
0     -0.976824 -1.015758 -0.864571 -1.202901 -1.243973 -1.091163 -1.121963   
1      0.317240  0.561588  0.676780 -0.057154  0.021664  0.052093 -0.360611   
2      1.693034  1.631441  1.522036  1.695976  1.635002  1.521992  1.688121   
3     -1.399097 -1.523252 -1.523374 -1.285726 -1.410870 -1.417807 -1.288077   
4      0.535188  0.602736  0.813512  0.522621  0.591895  0.805887  0.636070   
...         ...       ...       ...       ...       ...       ...       ...   
49995  0.194644  0.342131  0.763791  0.287950  0.424998  0.843577  0.345371   
49996  1.693034  1.494280 -0.006884  1.709780  1.551553  0.026966  1.715807   
49997 -1.303745  0.575304  1.273431 -1.244313  0.564079  1.346107 -1.232706   
49998  0.794000  1.027934  1.335582  0.771096  1.009138  1.308417  0.746812   
49999  1.338869  1.274823  1.323152  1.461305  1.412473  1.446613  1.425108   

              7         8         9  ...      3063      3064      3065  \
0     -1.231216 -1.127749 -0.882707  ...  1.395088  0.946620  0.403264   
1     -0.449900 -0.473116 -0.410588  ...  0.253645  0.118572  0.387855   
2      1.628957  1.515960  1.686173  ... -0.762709 -0.660768 -0.475092   
3     -1.412593 -1.417298 -1.243738  ... -1.137978 -1.277745 -1.322628   
4      0.680217  0.886505  0.714164  ... -0.809617 -0.758185 -0.490501   
...         ...       ...       ...  ...       ...       ...       ...   
49995  0.484888  0.911684  0.325361  ... -1.372521 -1.375162 -0.891155   
49996  1.573149  0.055626  1.700059  ...  1.911083  0.784258 -0.536731   
49997  0.554648  1.364891 -1.285396  ... -1.560155 -1.196563 -0.567550   
49998  0.987162  1.289356  0.728050  ...  1.066728  0.946620  0.850147   
49999  1.391772  1.440425  1.380684  ...  0.816548  0.832966  0.911786   

           3066      3067      3068      3069      3070      3071  Label  
0      0.380740 -0.123197 -0.458600 -0.056050 -0.540320 -0.641402      6  
1      0.256086  0.135572  0.430806  0.251995  0.114124  0.448238      9  
2     -0.741144 -0.656910 -0.473935 -0.718346 -0.636092 -0.459796      9  
3     -0.990451 -1.125930 -1.179326 -0.841564 -0.971295 -1.034884      4  
4     -0.865797 -0.818641 -0.550608 -0.826162 -0.779750 -0.520331      1  
...         ...       ...       ...       ...       ...       ...    ...  
49995 -1.411157 -1.417046 -0.933973 -1.380642 -1.386307 -0.913812      2  
49996  1.954493  0.895709 -0.504604  1.946241  0.880301 -0.580867      6  
49997 -1.644883 -1.336181 -0.734623 -1.765698 -1.514004 -0.974348      9  
49998  1.081917  1.025093  0.875510  1.052911  1.023960  0.856853      1  
49999  0.583302  0.620766  0.737498  0.560040  0.592985  0.705514      1  

[50000 rows x 3073 columns]

In [3]:
### Checking if the data if normally distributed or not...

## ERROR: Out of Memory

# from pingouin import multivariate_normality
# # Example dataset (replace with your actual data)
# data = df_images.iloc[:, :-1]  # Features (exclude the last column)

# # Perform the Multivariate Normality Test
# result = multivariate_normality(data, alpha=0.05)

# # Extract relevant information
# hz_statistic = result['hz']
# p_value = result['pval']
# is_normal = result['normal']

# # Print the results
# print(f"HzResults (hz={hz_statistic:.6f}, pval={p_value:.6f}, normal={is_normal})")

# # Interpretation
# if p_value > 0.05:
#     print("The data follows a multivariate normal distribution.")
# else:
#     print("The data does not follow a multivariate normal distribution.")


In [4]:
def dividingIntoClasses(df_images):
    """
    Creates separate DataFrames for each class based on the 'Label' column in the input DataFrame using Dictionary as a Dataform to store.

    Args:
        df_images (pandas.DataFrame): The input DataFrame containing image data.

    Returns:
        dict: A dictionary where keys are class labels and values are DataFrames containing data for each class.
    """
    class_dataframes = {}
    for class_label in range(10):
        class_dataframes[class_label] = df_images[df_images['Label'] == class_label]
    return class_dataframes

# Example usage:
# Assuming df_images is your original DataFrame
class_dataframes = dividingIntoClasses(df_images)
# Example: Access the DataFrame for class 'Airplane' (label 0)
airplane_df = class_dataframes[0]
print("Shape of Airplane DataFrame:", airplane_df.shape)
airplane_df  # Display the first few rows

Shape of Airplane DataFrame: (5000, 3073)


0         1         2         3         4         5         6  \
29     0.971083  0.931922  0.825942  0.991963  0.953506  0.843577  1.009825   
30    -0.064168 -0.247659 -0.280349 -0.112371 -0.284314 -0.299678 -0.069912   
35     1.638547  1.549144  1.459885  1.613151  1.523737  1.446613  1.605064   
49     1.693034  1.631441  1.522036  1.723584  1.662818  1.547119  1.715807   
77    -1.181150 -0.864882 -1.038594 -1.147684 -0.812822 -0.990657 -1.108121   
...         ...       ...       ...       ...       ...       ...       ...   
49921  1.693034  1.631441  1.522036  1.337067  1.301208  1.207911  1.189781   
49930  1.693034  1.631441  1.522036  1.723584  1.662818  1.547119  1.715807   
49941  0.834865  0.657601  0.453035  0.619250  0.577987  0.642565  0.442271   
49992  0.330862  0.259835  0.279012  0.329363  0.258101  0.278231  0.317686   
49994  0.344483  0.314699  0.390884  0.343167  0.313733  0.391300  0.345371   

              7         8         9  ...      3063      3064      3065  \
29     0.973210  0.861327  1.033539  ...  1.754721  1.823377  1.990469   
30    -0.240619 -0.271691 -0.063442  ...  0.019102 -0.108735 -0.074438   
35     1.517340  1.440425  1.616744  ... -0.137260  0.037391 -1.214760   
49     1.656861  1.541138  0.700278  ...  2.004900  2.099393  2.175386   
77    -0.770798 -0.951501 -1.077108  ... -1.137978 -0.839366 -0.968204   
...         ...       ...       ...  ...       ...       ...       ...   
49921  1.210395  1.113109  1.186283  ...  1.520178  1.677251  1.805552   
49930  1.656861  1.541138  1.713944  ...  2.004900  2.099393  2.175386   
49941  0.443032  0.685080  0.408676  ...  0.425643 -0.027554 -0.290175   
49992  0.247703  0.269640  0.311475  ...  0.112919 -0.124972 -0.660009   
49994  0.317463  0.382942  0.339247  ...  0.410007  0.573187  0.757689   

           3066      3067      3068      3069      3070      3071  Label  
29     1.751931  1.817576  1.979601  1.746012  1.790137  1.946493      0  
30    -0.008803 -0.123197 -0.105904 -0.086854 -0.205117 -0.187386      0  
35    -0.226947 -0.058505 -1.240665 -0.333290 -0.077421 -1.337561      0  
49     2.001238  2.092519  2.163616  1.977045  2.061492  2.128099      0  
77    -1.115105 -0.834814 -0.949307 -1.242022 -0.955332 -1.080285      0  
...         ...       ...       ...       ...       ...       ...    ...  
49921  1.518205  1.655845  1.780251  1.545783  1.678403  1.780020      0  
49930  2.001238  2.092519  2.163616  1.977045  2.061492  2.128099      0  
49941  0.396322 -0.009986 -0.243916  0.267397 -0.093383 -0.308457      0  
49992  0.131432 -0.123197 -0.642615  0.128777 -0.125307 -0.641402      0  
49994  0.396322  0.556073  0.737498  0.390615  0.545099  0.720648      0  

[5000 rows x 3073 columns]

In [5]:
def calculate_means(class_dataframes):
    """
    Calculates the mean of each column for each class DataFrame.

    Args:
        class_dataframes (dict): A dictionary where keys are class labels and values are DataFrames containing data for each class.

    Returns:
        dict: A dictionary where keys are class labels and values are Series containing the mean of each column.
    """
    class_means = {}
    for class_label, df in class_dataframes.items():
        # Calculate the mean of each column (excluding the 'Label' column)
        class_means[class_label] = df.drop('Label', axis=1).mean()
    return class_means

# Example usage:
# Assuming class_dataframes is your dictionary of class DataFrames
class_means = calculate_means(class_dataframes)
# Example: Access the mean values for class 'Airplane' (label 0)
airplane_means = class_means[0]
print("Mean values for Airplane class:")
airplane_means


Mean values for Airplane class:


0       0.194677
1       0.345377
2       0.567697
3       0.191252
4       0.344465
          ...   
3067    0.161521
3068    0.356881
3069    0.049579
3070    0.161885
3071    0.353076
Length: 3072, dtype: float64

In [6]:
def S_w(class_dataframes):
    """
    Calculates the within-class scatter matrix and displays each scaled covariance matrix.

    Args:
        class_dataframes (dict): A dictionary where keys are class labels and values are DataFrames containing data for each class.

    Returns:
        pandas.DataFrame: The within-class scatter matrix.
    """
    # Initialize an empty DataFrame to store the within-class scatter matrix
    scatter_matrix = pd.DataFrame(np.zeros((class_dataframes[0].shape[1]-1, class_dataframes[0].shape[1]-1)))

    for class_label, df in class_dataframes.items():
        # Drop the 'Label' column
        df_features = df.drop('Label', axis=1)

        # Calculate the covariance matrix of the features
        cov_matrix = df_features.cov()

        # Multiply the covariance matrix by the number of samples in the class
        scaled_cov_matrix = cov_matrix * df_features.shape[0]

        # # Display the scaled covariance matrix
        # print(f"Scaled Covariance Matrix for Class {class_label}:")
        # print(scaled_cov_matrix)
        # print("\n" + "="*50 + "\n")  # Print a separator

        # Add the scaled covariance matrix to the scatter matrix
        scatter_matrix += scaled_cov_matrix

    return scatter_matrix

# Example usage:
# Assuming class_dataframes is your dictionary of class DataFrames
within_class_scatter_matrix = S_w(class_dataframes)
print("Within-Class Scatter Matrix:")
within_class_scatter_matrix


Within-Class Scatter Matrix:


0             1             2             3             4     \
0     46978.627806  43259.593260  36851.726963  45730.056068  42044.837208   
1     43259.593260  44870.420846  39636.829523  42003.978237  43607.224885   
2     36851.726963  39636.829523  40748.292773  35780.828880  38569.866573   
3     45730.056068  42003.978237  35780.828880  46992.307170  43159.731941   
4     42044.837208  43607.224885  38569.866573  43159.731941  44832.646316   
...            ...           ...           ...           ...           ...   
3067  15235.090338  15966.082560  13751.265144  14963.965220  15712.746278   
3068  13848.712499  14653.346065  15387.619080  13575.426438  14395.066106   
3069  17041.093798  15372.473516  13047.534858  16554.244937  14889.577296   
3070  16033.926944  16773.552404  14454.799112  15508.282784  16274.576819   
3071  14576.012166  15393.194710  16055.090718  14056.900197  14898.405569   

              5             6             7             8             9     \
0     35680.747591  44097.682537  40485.442980  34295.864635  42855.766093   
1     38436.903376  40458.327655  41966.708906  36986.606427  39285.092552   
2     39661.975131  34441.951295  37155.532995  38244.886831  33410.729119   
3     36629.476299  45842.027244  42041.006344  35603.828907  44134.797827   
4     39491.751795  42046.077704  43647.783178  38422.398906  40423.456936   
...            ...           ...           ...           ...           ...   
3067  13500.616154  14705.410422  15472.591419  13289.984234  14425.109766   
3068  15156.177159  13307.083304  14155.926938  14941.820470  13022.417973   
3069  12587.913317  16214.782451  14555.489048  12288.244749  15931.204773   
3070  13980.904686  15148.798607  15934.628775  13688.250183  14841.220983   
3071  15595.954630  13700.924580  14571.779544  15306.619834  13399.564982   

      ...          3062          3063          3064          3065  \
0     ...  13051.072675  15766.030102  14727.422631  13399.686416   
1     ...  13874.537197  14108.246262  15470.654814  14213.948253   
2     ...  14682.142235  11976.442596  13328.183489  14989.495320   
3     ...  12821.835624  15570.458598  14493.419250  13165.404422   
4     ...  13651.839134  13886.579830  15246.910963  13988.271384   
...   ...           ...           ...           ...           ...   
3067  ...  41727.985034  44172.486577  47757.485906  43496.791059   
3068  ...  45456.437450  39543.804335  43382.122239  47234.348507   
3069  ...  36730.058633  44956.347383  42223.868902  38001.115496   
3070  ...  40221.475706  42119.802951  45511.437129  41569.850926   
3071  ...  43846.965189  37747.665106  41402.967759  45206.621748   

              3066          3067          3068          3069          3070  \
0     16269.346435  15235.090338  13848.712499  17041.093798  16033.926944   
1     14594.064965  15966.082560  14653.346065  15372.473516  16773.552404   
2     12380.054293  13751.265144  15387.619080  13047.534858  14454.799112   
3     16035.340073  14963.965220  13575.426438  16554.244937  15508.282784   
4     14340.901407  15712.746278  14395.066106  14889.577296  16274.576819   
...            ...           ...           ...           ...           ...   
3067  45441.405166  49094.825919  44612.081139  44136.974104  47576.449509   
3068  40718.990502  44612.081139  48388.997000  39624.034580  43326.250624   
3069  46940.417018  44136.974104  39624.034580  48398.746173  45569.262477   
3070  44066.282799  47576.449509  43326.250624  45569.262477  49074.818331   
3071  39513.946345  43278.507145  47015.105418  40920.056422  44675.566925   

              3071  
0     14576.012166  
1     15393.194710  
2     16055.090718  
3     14056.900197  
4     14898.405569  
...            ...  
3067  43278.507145  
3068  47015.105418  
3069  40920.056422  
3070  44675.566925  
3071  48332.594538  

[3072 rows x 3072 columns]

In [7]:
def S_b(class_dataframes, class_means):
    """
    Calculates the between-class scatter matrix.

    Args:
        class_dataframes (dict): A dictionary where keys are class labels and values are DataFrames containing data for each class.
        class_means (dict): A dictionary where keys are class labels and values are Series containing the mean of each column.

    Returns:
        pandas.DataFrame: The between-class scatter matrix.
    """
    # Calculate the overall mean of all classes
    overall_mean = pd.concat(class_dataframes.values()).drop('Label', axis=1).mean()

    # Initialize an empty DataFrame to store the between-class scatter matrix
    scatter_matrix = pd.DataFrame(np.zeros((class_dataframes[0].shape[1]-1, class_dataframes[0].shape[1]-1)))

    for class_label, df in class_dataframes.items():
        # Calculate the mean difference (mean vector - overall mean)
        mean_diff = class_means[class_label] - overall_mean

        # Multiply the outer product of the mean difference by the number of samples in the class
        scaled_outer_product = np.outer(mean_diff, mean_diff) * df.shape[0]

        # Add the scaled outer product to the scatter matrix
        scatter_matrix += scaled_outer_product

    return scatter_matrix

# Example usage:
# Assuming class_dataframes is your dictionary of class DataFrames
# and class_means is your dictionary of class means
between_class_scatter_matrix = S_b(class_dataframes, class_means)
print("Between-Class Scatter Matrix:")
between_class_scatter_matrix

Between-Class Scatter Matrix:


0            1            2            3            4     \
0     3030.767920  3846.623522  5010.878519  3023.016553  3856.131512   
1     3846.623522  5138.553238  6778.961710  3834.812424  5156.234564   
2     5010.878519  6778.961710  9259.856886  4990.696533  6797.550840   
3     3023.016553  3834.812424  4990.696533  3017.091292  3846.252729   
4     3856.131512  5156.234564  6797.550840  3846.252729  5176.320213   
...           ...          ...          ...          ...          ...   
3067   586.297756   707.178060   721.289174   585.576513   709.021148   
3068  1749.048805  2246.576567  3187.435611  1750.189676  2256.264138   
3069   280.549335    55.922906  -276.097732   276.860584    45.056589   
3070   696.765277   849.458015   908.965081   694.487798   850.335738   
3071  1832.156003  2353.873130  3321.816167  1831.748339  2362.494420   

             5            6            7            8            9     ...  \
0     5033.815344  3021.462016  3873.881062  5059.499794  3026.677257  ...   
1     6814.945425  3833.745872  5183.824953  6853.154152  3845.643171  ...   
2     9307.519293  4988.382477  6831.770781  9356.370639  5014.254979  ...   
3     5015.006164  3016.275994  3864.783828  5041.433220  3021.251183  ...   
4     6835.413296  3846.056672  5205.077854  6874.802554  3857.848890  ...   
...           ...          ...          ...          ...          ...  ...   
3067   722.249353   584.160494   711.731249   725.547453   575.297298  ...   
3068  3206.024339  1749.061849  2265.732374  3221.098718  1757.077626  ...   
3069  -289.911163   272.863521    38.700817  -297.629481   256.990054  ...   
3070   909.868607   692.720256   853.473907   913.884122   684.002515  ...   
3071  3340.042172  1830.277157  2372.243832  3355.589497  1838.173674  ...   

             3062         3063         3064         3065         3066  \
0     1548.358741    52.984680   473.371136  1650.817952   160.023305   
1     1983.464173  -242.059389   561.589697  2118.798200  -104.635553   
2     2867.771877  -659.752708   541.371974  3029.602235  -491.740974   
3     1550.330653    50.993585   473.141319  1652.539741   157.668745   
4     1992.263033  -252.821189   563.099880  2128.291784  -114.994109   
...           ...          ...          ...          ...          ...   
3067   490.097798  1037.475902   895.568348   498.015118  1063.631988   
3068  1553.261507   128.808190   462.689307  1585.892803   178.018517   
3069   253.810767  1610.217027  1065.684374   243.756020  1624.887661   
3070   529.278222  1017.771240   896.195788   543.204742  1049.476931   
3071  1568.588573   121.371221   467.376525  1606.541505   175.390725   

             3067         3068         3069         3070         3071  
0      586.297756  1749.048805   280.549335   696.765277  1832.156003  
1      707.178060  2246.576567    55.922906   849.458015  2353.873130  
2      721.289174  3187.435611  -276.097732   908.965081  3321.816167  
3      585.576513  1750.189676   276.860584   694.487798  1831.748339  
4      709.021148  2256.264138    45.056589   850.335738  2362.494420  
...           ...          ...          ...          ...          ...  
3067   914.993046   509.245023  1072.004385   921.621330   519.139126  
3068   509.245023  1620.680799   241.826813   560.081418  1646.320501  
3069  1072.004385   241.826813  1610.933576  1064.813257   244.847040  
3070   921.621330   560.081418  1064.813257   934.996633   575.616368  
3071   519.139126  1646.320501   244.847040   575.616368  1677.071981  

[3072 rows x 3072 columns]

In [8]:

# Calculate the inverse of the within-class scatter matrix
Sw_inv = np.linalg.inv(within_class_scatter_matrix)

# Multiply the inverse of the within-class scatter matrix with the between-class scatter matrix
result = np.dot(Sw_inv, between_class_scatter_matrix)

# Convert the result to a DataFrame
result_df = pd.DataFrame(result)

# Display the DataFrame
result_df

0         1         2         3         4         5         6     \
0     0.022510  0.029834  0.051603  0.023498  0.030943  0.052681  0.023507   
1    -0.165575 -0.225900 -0.312038 -0.167682 -0.229603 -0.315996 -0.168732   
2     0.239597  0.316513  0.418958  0.239982  0.318808  0.422144  0.240912   
3     0.027407  0.043144  0.030845  0.027054  0.043450  0.031053  0.027706   
4     0.089614  0.105967  0.161406  0.090684  0.107230  0.162955  0.090546   
...        ...       ...       ...       ...       ...       ...       ...   
3067  0.036105  0.043310  0.026992  0.035067  0.042400  0.026148  0.034343   
3068 -0.044900 -0.052156 -0.062671 -0.044861 -0.052112 -0.062805 -0.044190   
3069 -0.034792 -0.050266 -0.082764 -0.035553 -0.051366 -0.084015 -0.035590   
3070 -0.016093 -0.003036  0.012734 -0.016453 -0.003095  0.012886 -0.016770   
3071  0.041176  0.038086  0.047299  0.041866  0.038628  0.047829  0.041961   

          7         8         9     ...      3062      3063      3064  \
0     0.031126  0.053056  0.023446  ...  0.046144 -0.002377  0.008391   
1    -0.231962 -0.318836 -0.169473  ... -0.126036  0.003377 -0.041258   
2     0.321456  0.425285  0.241858  ...  0.125432  0.004447  0.048268   
3     0.044589  0.032027  0.027739  ... -0.036481 -0.003784  0.002499   
4     0.107301  0.163473  0.091162  ...  0.094946 -0.003827  0.008769   
...        ...       ...       ...  ...       ...       ...       ...   
3067  0.042186  0.026032  0.033008  ... -0.009548  0.022766  0.020705   
3068 -0.051905 -0.062822 -0.043132  ... -0.028945  0.001166 -0.005047   
3069 -0.051611 -0.084434 -0.036278  ... -0.032435  0.039129  0.021891   
3070 -0.003429  0.012568 -0.016000  ... -0.000483 -0.022454 -0.011171   
3071  0.038848  0.048183  0.041713  ...  0.022142 -0.014552 -0.013930   

          3065      3066      3067      3068      3069      3070      3071  
0     0.044753 -0.002834  0.007672  0.043669 -0.002938  0.007129  0.042430  
1    -0.129710 -0.001281 -0.045923 -0.133373 -0.006105 -0.049166 -0.134784  
2     0.134171  0.013458  0.057831  0.142581  0.022992  0.066044  0.148778  
3    -0.031039 -0.000040  0.006631 -0.026800  0.002702  0.009393 -0.023530  
4     0.093549 -0.003939  0.008503  0.092864 -0.003242  0.008534  0.091375  
...        ...       ...       ...       ...       ...       ...       ...  
3067 -0.005956  0.026141  0.023992 -0.003114  0.029102  0.027364  0.000456  
3068 -0.029707 -0.000362 -0.006563 -0.030405 -0.002651 -0.009069 -0.032215  
3069 -0.030719  0.040541  0.022952 -0.029358  0.040813  0.023464 -0.028036  
3070 -0.004061 -0.025519 -0.013966 -0.006878 -0.027506 -0.015998 -0.008801  
3071  0.023803 -0.013130 -0.012405  0.025085 -0.011538 -0.010774  0.025933  

[3072 rows x 3072 columns]

In [9]:
import numpy as np

def sorted_eigenvectors(df):
    """
    Calculates the eigenvalues and eigenvectors of a DataFrame and returns the eigenvectors sorted by their corresponding eigenvalues in descending order.

    Args:
        df (pandas.DataFrame): The input DataFrame.

    Returns:
        list: A list of tuples where each tuple contains an eigenvalue and its corresponding eigenvector. The list is sorted in descending order of the eigenvalues.
    """
    # Calculate the eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(df)

    # Create a list of tuples where each tuple is an eigenvalue and its corresponding eigenvector
    eig_pairs = [(np.abs(eigenvalues[i]), eigenvectors[:, i]) for i in range(len(eigenvalues))]

    # Sort the list of tuples in descending order of the eigenvalues
    eig_pairs.sort(key=lambda x: x[0], reverse=True)

    return eig_pairs

# Example usage:
# Assuming result_df is your DataFrame
eig_pairs = sorted_eigenvectors(result_df)
# Example: Access the eigenvector corresponding to the largest eigenvalue
largest_eigenvector = eig_pairs[1][1]
print("Eigenvector corresponding to the largest eigenvalue:")
print(largest_eigenvector)

print("Shape of the largest eigenvector:", largest_eigenvector.shape)
eig_pairs

Eigenvector corresponding to the largest eigenvalue:
[ 0.00781854+0.j -0.01119318+0.j -0.00017411+0.j ... -0.02114909+0.j
  0.03043463+0.j -0.01059802+0.j]
Shape of the largest eigenvector: (3072,)


[(0.8807282267224639,
  array([-0.00814298+0.j,  0.04085002+0.j, -0.05253728+0.j, ...,
          0.00844308+0.j,  0.00581161+0.j, -0.01068111+0.j])),
 (0.42650619541944335,
  array([ 0.00781854+0.j, -0.01119318+0.j, -0.00017411+0.j, ...,
         -0.02114909+0.j,  0.03043463+0.j, -0.01059802+0.j])),
 (0.310042319767007,
  array([ 0.00743221+0.j,  0.01346363+0.j, -0.03484917+0.j, ...,
         -0.00914372+0.j, -0.00289569+0.j,  0.01239637+0.j])),
 (0.20771067382846176,
  array([ 0.00680144+0.j, -0.0008233 +0.j, -0.0086951 +0.j, ...,
          0.00455177+0.j, -0.00501069+0.j, -0.00103078+0.j])),
 (0.1816860446339414,
  array([ 0.00066536+0.j, -0.00744698+0.j,  0.00052814+0.j, ...,
          0.01508535+0.j, -0.01291532+0.j, -0.00438569+0.j])),
 (0.13115654534128537,
  array([ 0.01401552+0.j, -0.03034074+0.j,  0.0106756 +0.j, ...,
         -0.01403494+0.j,  0.00891069+0.j,  0.00057914+0.j])),
 (0.11923252726809992,
  array([ 0.01196722+0.j, -0.00128207+0.j, -0.00964603+0.j, ...,
          

In [15]:
def reduce_and_add_last_column(class_dataframes, eig_pairs, k):
    """
    Reduces the dimensionality of each DataFrame in class_dataframes from n to k using the top k eigenvectors
    and adds the last column from each original DataFrame to the reduced DataFrame.

    Args:
        class_dataframes (dict): A dictionary where keys are class labels and values are original DataFrames containing data for each class.
        eig_pairs (list): A list of tuples where each tuple contains an eigenvalue and its corresponding eigenvector. The list is sorted in descending order of the eigenvalues.
        k (int): The number of dimensions to reduce to.

    Returns:
        dict: A dictionary where keys are class labels and values are DataFrames containing data for each class, with reduced dimensionality and an additional column.
    """
    # Get the top k eigenvectors
    top_k_eigenvectors = np.array([eig_pairs[i][1] for i in range(k)]).T

    # Initialize an empty dictionary to store the reduced DataFrames
    reduced_dataframes = {}

    for class_label, df in class_dataframes.items():
        # Drop the 'Label' column
        df_features = df.drop('Label', axis=1)

        # Perform the dimensionality reduction
        reduced_features = np.dot(df_features, top_k_eigenvectors)

        # Create a new DataFrame with the reduced features
        reduced_df = pd.DataFrame(reduced_features)

        # Store the last column from the original DataFrame
        last_column = df.iloc[:, -1]

        # Add the last column to the reduced DataFrame
        reduced_df['Last_Column'] = last_column.values

        # Store the reduced DataFrame in the dictionary
        reduced_dataframes[class_label] = reduced_df

    return reduced_dataframes

# Example usage:
# Assuming class_dataframes is your dictionary of class DataFrames
# and eig_pairs is your list of eigenvalue-eigenvector pairs
k = 50  # The number of dimensions to reduce to
reduced_dataframes = reduce_and_add_last_column(class_dataframes, eig_pairs, k)
# Example: Access the reduced DataFrame for class 'Airplane' (label 0)
reduced_airplane_df = reduced_dataframes[0]
print("Shape of reduced Airplane DataFrame:", reduced_airplane_df.shape)
reduced_airplane_df  # Display the first few rows


Shape of reduced Airplane DataFrame: (5000, 51)


0                   1                   2  \
0    -0.088478+0.000000j -0.055128+0.000000j -0.011355+0.000000j   
1    -0.017232+0.000000j  0.020457+0.000000j -0.031810+0.000000j   
2     0.023285+0.000000j -0.018264+0.000000j -0.148633+0.000000j   
3    -0.046063+0.000000j  0.038429+0.000000j -0.034841+0.000000j   
4    -0.011186+0.000000j -0.013940+0.000000j  0.024280+0.000000j   
...                  ...                 ...                 ...   
4995 -0.032023+0.000000j  0.032902+0.000000j -0.000479+0.000000j   
4996 -0.080622+0.000000j -0.044427+0.000000j  0.011596+0.000000j   
4997  0.022888+0.000000j  0.044869+0.000000j -0.019673+0.000000j   
4998 -0.012795+0.000000j  0.031703+0.000000j -0.051322+0.000000j   
4999 -0.054264+0.000000j  0.021368+0.000000j  0.025997+0.000000j   

                       3                   4                   5  \
0    -0.002951+0.000000j  0.092507+0.000000j  0.030191+0.000000j   
1     0.045163+0.000000j -0.018044+0.000000j  0.044644+0.000000j   
2    -0.000074+0.000000j -0.017767+0.000000j  0.020675+0.000000j   
3     0.014751+0.000000j -0.049019+0.000000j  0.038731+0.000000j   
4     0.043054+0.000000j  0.037168+0.000000j -0.041358+0.000000j   
...                  ...                 ...                 ...   
4995 -0.025931+0.000000j -0.011012+0.000000j  0.034746+0.000000j   
4996  0.022087+0.000000j  0.030896+0.000000j  0.035636+0.000000j   
4997 -0.028644+0.000000j -0.022679+0.000000j  0.007512+0.000000j   
4998  0.006807+0.000000j -0.025457+0.000000j  0.027739+0.000000j   
4999  0.001537+0.000000j  0.000704+0.000000j -0.009271+0.000000j   

                       6                   7                   8  \
0     0.026500+0.000000j -0.024505+0.000000j  0.000778+0.000000j   
1     0.012762+0.000000j  0.012486+0.000000j  0.024136+0.000000j   
2    -0.011556+0.000000j -0.059404+0.000000j  0.040175+0.000000j   
3     0.067699+0.000000j -0.052826+0.000000j -0.006247+0.000000j   
4    -0.000383+0.000000j -0.015683+0.000000j  0.016834+0.000000j   
...                  ...                 ...                 ...   
4995 -0.006440+0.000000j -0.027470+0.000000j  0.023953+0.000000j   
4996  0.022244+0.000000j -0.034763+0.000000j -0.017186+0.000000j   
4997  0.033488+0.000000j -0.020307+0.000000j  0.012642+0.000000j   
4998  0.007830+0.000000j  0.000705+0.000000j -0.016908+0.000000j   
4999  0.008499+0.000000j -0.007754+0.000000j  0.007277+0.000000j   

                       9  ...                  41                  42  \
0    -0.031161+0.000000j  ... -0.059605+0.000000j  0.194688+0.002922j   
1    -0.020282+0.000000j  ... -0.094730+0.000000j  0.026067+0.070390j   
2    -0.024152+0.000000j  ...  0.099537+0.000000j -0.034497-0.004308j   
3    -0.055061+0.000000j  ...  0.351022+0.000000j  0.115683+0.016766j   
4     0.020513+0.000000j  ... -0.123835+0.000000j -0.020300+0.067096j   
...                  ...  ...                 ...                 ...   
4995 -0.093578+0.000000j  ...  0.046749+0.000000j -0.151953-0.154535j   
4996  0.008473+0.000000j  ...  0.096291+0.000000j  0.176202+0.099632j   
4997  0.054125+0.000000j  ...  0.038803+0.000000j  0.124771+0.017578j   
4998  0.063573+0.000000j  ...  0.147752+0.000000j  0.025694+0.126175j   
4999  0.027411+0.000000j  ... -0.083852+0.000000j -0.006953+0.069654j   

                      43                  44                  45  \
0     0.194688-0.002922j -0.162574-0.118153j -0.162574+0.118153j   
1     0.026067-0.070390j  0.044242-0.007109j  0.044242+0.007109j   
2    -0.034497+0.004308j -0.068102+0.002563j -0.068102-0.002563j   
3     0.115683-0.016766j -0.022779-0.005629j -0.022779+0.005629j   
4    -0.020300-0.067096j  0.155337+0.131579j  0.155337-0.131579j   
...                  ...                 ...                 ...   
4995 -0.151953+0.154535j -0.147444-0.002431j -0.147444+0.002431j   
4996  0.176202-0.099632j  0.197676+0.029903j  0.197676-0.029903j   
4997  0.124771-0.017578j  0.009270-0.144959j  0.009270+0.144959j   
4998  0.025694-